name: easy_download_manager
description: A new Flutter package to handle download queue logic.
version: 0.0.1
homepage: https://github.com/rlazom/easy_download_manager

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # A string-based path manipulation library
  path: ^1.8.3

  collection: ^1.17.2

  # Flutter plugin for getting commonly used locations on host platform file systems,
  # such as the temp and app data directories.
  path_provider: ^2.1.1

  # A powerful HTTP networking package, supports Interceptors,
  # Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.1.1

  # Flutter plugin for reading and writing simple key-value pairs
  shared_preferences: ^2.2.2

  # An SVG rendering and widget library for Flutter
  flutter_svg: ^2.0.5

  # RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
  uuid: ^3.0.7

  # Removes common accents and diacritical signs from a string by replacing them with an
  # equivalent character.
  diacritic: ^0.1.4

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.2

  # Provides easy access to useful information about the system
  # (architecture, bitness, kernel, memory, operating system, CPU, user).
  system_info2: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
